WAZO-2943: Wazo teams integration
wazo-platform/wazo-chatd pull request #110
Opened 2022-12-13 18:10 UTC by ja0x

Depends-On: https://github.com/wazo-platform/wazo-test-helpers/pull/81

Adds a plugin for chatd that allows Microsoft Teams to synchronize it's presence with Wazo.

Usage:
1. plugin is disabled by default, enable in config
    ``` yaml
    enabled_plugins:
      teams_presence: true
    ```
2. connect a user and enable `microsoft office365` integration
3. changes of presence in teams should be reflected in chatd
4. disable `microsoft office365` integration to stop presence synchronization

2022-12-13 18:14 UTC, ja0x commented
recheck

2022-12-13 18:21 UTC, ja0x commented
recheck

2022-12-13 19:13 UTC, ja0x commented
recheck

2022-12-14 13:36 UTC, pc-m requested changes

2022-12-14 14:12 UTC, ja0x commented on wazo_chatd/plugins/teams/plugin.py
> +# Copyright 2022-2022 The Wazo Authors  (see the AUTHORS file)
done

2022-12-14 16:07 UTC, pc-m approved these changes

2022-12-14 16:16 UTC, merged